version: '2'
services:
    withentities-app:
        image: withentities
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://withentities-mysql:3306/withentities?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    withentities-mysql:
        extends:
            file: mysql.yml
            service: withentities-mysql
