version: '2'
services:
    justgenerated-app:
        image: justgenerated
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://justgenerated-mysql:3306/justgenerated?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    justgenerated-mysql:
        extends:
            file: mysql.yml
            service: justgenerated-mysql
